# Generated by Django 2.0.5 on 2019-02-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funny_Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_embed_code', models.TextField(verbose_name='video_embed_code')),
                ('on_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
