# Generated by Django 2.0.5 on 2019-02-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangla_Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangla_jokes.Bangla_Jokes')),
            ],
        ),
    ]
