# Generated by Django 2.0.5 on 2019-02-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0002_bangla_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangla_views',
            old_name='content',
            new_name='title',
        ),
    ]
