# Generated by Django 2.0.5 on 2019-02-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0003_auto_20190221_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangla_views',
            old_name='title',
            new_name='content',
        ),
    ]
