# Generated by Django 2.0.5 on 2019-02-21 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0004_auto_20190221_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangla_views',
            name='id',
        ),
        migrations.AlterField(
            model_name='bangla_views',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bangla_jokes.Bangla_Jokes'),
        ),
    ]
