# Generated by Django 2.0.5 on 2019-02-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0005_auto_20190221_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangla_views',
            name='content',
        ),
        migrations.DeleteModel(
            name='Bangla_Views',
        ),
    ]
