# Generated by Django 2.0.5 on 2019-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0006_auto_20190221_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangla_jokes',
            name='visit_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
