# Generated by Django 2.0.5 on 2019-02-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bangla_jokes', '0007_bangla_jokes_visit_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangla_jokes',
            name='visit_num',
        ),
    ]
